/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import koneksi.Database;

/**
 *
 * @author Dosen
 */
public class MenuAkademik extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuAkademik
     */
    public MenuAkademik() {
        initComponents();
        setTitle("Sistem Informasi Akademik");
        setSize(1000, 600);
        setLocationRelativeTo(this);
        koneksi.Database.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuMahasiswa = new javax.swing.JMenuItem();
        mnuMatakuliah = new javax.swing.JMenuItem();
        mnuPeriode = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuKeluar = new javax.swing.JMenuItem();
        mnuTransaksi = new javax.swing.JMenu();
        mnuKRS = new javax.swing.JMenuItem();
        mnuLaporan = new javax.swing.JMenu();
        mnuCetakDaftarMahasiswa = new javax.swing.JMenuItem();
        mnuCetakDaftarMatakuliah = new javax.swing.JMenuItem();
        mnuCetakKRS = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuFile.setText("File");

        mnuMahasiswa.setText("Entri Data Mahasiswa");
        mnuMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMahasiswaActionPerformed(evt);
            }
        });
        mnuFile.add(mnuMahasiswa);

        mnuMatakuliah.setText("Entri Data Matakuliah");
        mnuFile.add(mnuMatakuliah);

        mnuPeriode.setText("Entri Data Periode");
        mnuFile.add(mnuPeriode);
        mnuFile.add(jSeparator1);

        mnuKeluar.setText("Keluar");
        mnuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKeluarActionPerformed(evt);
            }
        });
        mnuFile.add(mnuKeluar);

        jMenuBar1.add(mnuFile);

        mnuTransaksi.setText("Transaksi");

        mnuKRS.setText("KRS");
        mnuTransaksi.add(mnuKRS);

        jMenuBar1.add(mnuTransaksi);

        mnuLaporan.setText("Laporan");

        mnuCetakDaftarMahasiswa.setText("Cetak Daftar Mahasiswa");
        mnuLaporan.add(mnuCetakDaftarMahasiswa);

        mnuCetakDaftarMatakuliah.setText("Cetak Daftar Matakuliah");
        mnuLaporan.add(mnuCetakDaftarMatakuliah);

        mnuCetakKRS.setText("Cetak KRS");
        mnuLaporan.add(mnuCetakKRS);

        jMenuBar1.add(mnuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 507, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuKeluarActionPerformed

    private void mnuMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMahasiswaActionPerformed
        view.FrmMahasiswa objMhs = new view.FrmMahasiswa();
        objMhs.setVisible(true);
    }//GEN-LAST:event_mnuMahasiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAkademik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAkademik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuCetakDaftarMahasiswa;
    private javax.swing.JMenuItem mnuCetakDaftarMatakuliah;
    private javax.swing.JMenuItem mnuCetakKRS;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuKRS;
    private javax.swing.JMenuItem mnuKeluar;
    private javax.swing.JMenu mnuLaporan;
    private javax.swing.JMenuItem mnuMahasiswa;
    private javax.swing.JMenuItem mnuMatakuliah;
    private javax.swing.JMenuItem mnuPeriode;
    private javax.swing.JMenu mnuTransaksi;
    // End of variables declaration//GEN-END:variables
}
